<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_infokatalon.com_fa fa-twitter fa-fw fa-3x</name>
   <tag></tag>
   <elementGuidId>1ecd8308-4bd4-4597-8648-05e6175543db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-twitter.fa-fw.fa-3x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[2]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>11fb1f53-d713-4495-9286-4c1d21c02640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-twitter fa-fw fa-3x</value>
      <webElementGuid>8bb785f0-91b0-4d08-9c92-e1ddc497dbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/footer[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-10 col-lg-offset-1 text-center&quot;]/ul[@class=&quot;list-inline&quot;]/li[2]/a[1]/i[@class=&quot;fa fa-twitter fa-fw fa-3x&quot;]</value>
      <webElementGuid>9544837f-1442-4712-90b9-b308c339a6be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/i</value>
      <webElementGuid>a6e1793b-c414-4b41-8195-5bd146052091</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
